private const val PREF_USQUE_ENABLED = "pref_usque_enabled"
private const val PREF_USQUE_REGISTERED = "pref_usque_registered"
private const val PREF_USQUE_TUN_IF = "pref_usque_tun_if"
private const val PREF_USQUE_TUN_IP4 = "pref_usque_tun_ipv4"
private const val PREF_USQUE_TUN_IP6 = "pref_usque_tun_ipv6"

var usqueEnabled: Boolean          // ONE definition only
    get() = ...
    set(value) = ...

var usqueRegistered: Boolean
    get() = ...
    set(value) = ...

var usqueTunInterface: String?
    get() = ...
    set(value) = ...

var usqueTunIpv4: String?
    get() = ...
    set(value) = ...

var usqueTunIpv6: String?
    get() = ...
    set(value) = ...
